# my first ci file

name: My First CI Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Welcome message
        run: echo "Hello, World! This is my first CI pipeline."

      - name: Show Date and Time
        run: date

      - name: List all files in the repository
        run: ls -la

      - name: Show Branch Name
        run: echo "Current branch: ${{ github.ref }}"